
SET SCHEMA "DM_PAL_TEST";
DROP TYPE PAL_KMEANS_DATA_T;
CREATE TYPE PAL_KMEANS_DATA_T AS TABLE(
"IP" VARCHAR(16),
"SrcIPNum" DOUBLE,
"DestIPNum" DOUBLE,
"SrcPortNum" DOUBLE,
"DestPortNum" DOUBLE,
"PacketsNum" DOUBLE,
"BytesNum" DOUBLE,
"Protocol" VARCHAR(4)
);
DROP TYPE PAL_CONTROL_T;
CREATE TYPE PAL_CONTROL_T AS TABLE(
"NAME" VARCHAR (100),
"INTARGS" INTEGER,
"DOUBLEARGS" DOUBLE,
"STRINGARGS" VARCHAR (100)
);
DROP TYPE PAL_KMEANS_ASSIGNED_T;
CREATE TYPE PAL_KMEANS_ASSIGNED_T AS TABLE(
"ID" INTEGER,
"CLUSTER" INTEGER,
"DISTANCE" DOUBLE,
"SLIGHT_SILHOUETTE" DOUBLE
);
DROP TYPE PAL_KMEANS_CENTERS_T;
CREATE TYPE PAL_KMEANS_CENTERS_T AS TABLE(
"IP" VARCHAR(16),
"SrcIPNum" DOUBLE,
"DestIPNum" DOUBLE,
"SrcPortNum" DOUBLE,
"DestPortNum" DOUBLE,
"PacketsNum" DOUBLE,
"BytesNum" DOUBLE,
"Protocol" VARCHAR(4)
);
DROP TABLE PAL_KMEANS_PDATA_TBL;
CREATE COLUMN TABLE PAL_KMEANS_PDATA_TBL("POSITION" INT, "SCHEMA_NAME" NVARCHAR(256), "TYPE_NAME" NVARCHAR(256), "PARAMETER_TYPE" VARCHAR(7));
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (1, 'DM_PAL_TEST', 'PAL_KMEANS_DATA_T', 'IN');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (2, 'DM_PAL_TEST', 'PAL_CONTROL_T', 'IN');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (3, 'DM_PAL_TEST', 'PAL_KMEANS_ASSIGNED_T', 'OUT');
INSERT INTO PAL_KMEANS_PDATA_TBL VALUES (4, 'DM_PAL_TEST', 'PAL_KMEANS_CENTERS_T', 'OUT');
CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_DROP('DM_PAL_TEST', 'PAL_KMEANS_PROC');
CALL "SYS".AFLLANG_WRAPPER_PROCEDURE_CREATE('AFLPAL', 'KMEANS', 'DM_PAL_TEST', 'PAL_KMEANS_PROC', PAL_KMEANS_PDATA_TBL);

DROP TABLE #PAL_CONTROL_TBL;
CREATE LOCAL TEMPORARY COLUMN TABLE #PAL_CONTROL_TBL(
"NAME" VARCHAR (100),
"INTARGS" INTEGER,
"DOUBLEARGS" DOUBLE,
"STRINGARGS" VARCHAR (100)
);
INSERT INTO #PAL_CONTROL_TBL VALUES ('THREAD_NUMBER', 2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('GROUP_NUMBER', 2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('INIT_TYPE', 1, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('DISTANCE_LEVEL',2, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('MAX_ITERATION', 100, null, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('EXIT_THRESHOLD', null, 1.0E-6, null);
INSERT INTO #PAL_CONTROL_TBL VALUES ('CATEGORY_WEIGHTS', null, 0.5, null);

DROP TABLE PAL_KMEANS_ASSIGNED_TBL;
CREATE COLUMN TABLE PAL_KMEANS_ASSIGNED_TBL LIKE PAL_KMEANS_ASSIGNED_T;
DROP TABLE PAL_KMEANS_CENTERS_TBL;
CREATE COLUMN TABLE PAL_KMEANS_CENTERS_TBL LIKE PAL_KMEANS_CENTERS_T;
DROP TABLE PAL_KMEANS_SIL_CENTERS_TBL;
CREATE COLUMN TABLE PAL_KMEANS_SIL_CENTERS_TBL LIKE PAL_KMEANS_SIL_CENTERS_T;


CALL "DM_PAL_TEST".PAL_KMEANS_PROC(PAL_KMEANS_DATA_TBL, PAL_CONTROL_TBL, 
PAL_KMEANS_ASSIGNED_TBL, PAL_KMEANS_CENTERS_TBL) with OVERVIEW;

SELECT * FROM PAL_KMEANS_ASSIGNED_TBL;
SELECT * FROM PAL_KMEANS_CENTERS_TBL;

